### ISSUE TITLE
发现一个好东西

### ISSUE THREAD

**Issue by 32R34L** [yijiebuyi/3DWheelPicker#1]
首先谢谢作者的开源，这个框架确实比其他的框架滑动起来丝滑很多。
之前因为这个问题没有达到我的预期，奈何自定义view我是个渣渣，只能用NumberPicker搞了组合控件使用。
不过我刚下载了Demo就发现了一个问题，选择时间可以选择到59点，这个希望作者看一下。
还有希望作者提供一些修改UI风格的方法，字体大小，颜色，阻尼等。

**Comment by yijiebuyi** [comment]
感谢反馈，bug已修复

ui的风格，见mk文件中设置Pickerview样式代码，PickOption描述了对外开放的样式设置

**Comment by yijiebuyi** [comment]
> 首先谢谢作者的开源，这个框架确实比其他的框架滑动起来丝滑很多。
> 之前因为这个问题没有达到我的预期，奈何自定义view我是个渣渣，只能用NumberPicker搞了组合控件使用。
> 不过我刚下载了Demo就发现了一个问题，选择时间可以选择到59点，这个希望作者看一下。
> 还有希望作者提供一些修改UI风格的方法，字体大小，颜色，阻尼等。

感谢反馈，问题已修复，见mk文档描述

**Comment by 32R34L** [comment]
> > 首先谢谢作者的开源，这个框架确实比其他的框架滑动起来丝滑很多。
> > 之前因为这个问题没有达到我的预期，奈何自定义view我是个渣渣，只能用NumberPicker搞了组合控件使用。
> > 不过我刚下载了Demo就发现了一个问题，选择时间可以选择到59点，这个希望作者看一下。
> > 还有希望作者提供一些修改UI风格的方法，字体大小，颜色，阻尼等。
> 
> 感谢反馈，问题已修复，见mk文档描述

1：默认的小时单位，是“点”好，还是“时”好？
2：HeadView有对外开放的方法吗，HeadView的backgroundColor，可否添加个中间的title？textColor，textSize等。
3：pickDate选取时间只能获取前后几年的数据，如果我想获取某个时间段的时间好像就不能了，
　比如我想在2000-05-05到2020-03-20这个时间段内选取一个时间点就不行了。
　更极限的在2000-05-05 12:20:31到2020-03-20 19:40:33这个时间段呢。
　作者可以开放个方法
　pickDate(Context context, @Nullable Date initDate, Date witchPickVisible, Date startDate, Date endDate, final 　OnDatePickListener listener)
4：OnDatePickListener 回调的参数有点多，如果可以，希望返回DateWheelPicker？这样就可以直接通过picker.getSelectedYear()等获取想要的值。
5：application中全局统一style

**Comment by yijiebuyi** [comment]
> application中全局统一style

1.在你的app的字符串资源文件添加<string name="_hour">时</string>就解决你的问题
2.看BottomSheet中的方法
3.目前没有实现
4.可以考虑优化
5.目前Datapicker类中的静态方法是为了展示用法，看效果，所以style都在这里设置。

**Comment by yijiebuyi** [comment]
> > > 首先谢谢作者的开源，这个框架确实比其他的框架滑动起来丝滑很多。
> > > 之前因为这个问题没有达到我的预期，奈何自定义view我是个渣渣，只能用NumberPicker搞了组合控件使用。
> > > 不过我刚下载了Demo就发现了一个问题，选择时间可以选择到59点，这个希望作者看一下。
> > > 还有希望作者提供一些修改UI风格的方法，字体大小，颜色，阻尼等。
> > 
> > 
> > 感谢反馈，问题已修复，见mk文档描述
> 
> 1：默认的小时单位，是“点”好，还是“时”好？
> 2：HeadView有对外开放的方法吗，HeadView的backgroundColor，可否添加个中间的title？textColor，textSize等。
> 3：pickDate选取时间只能获取前后几年的数据，如果我想获取某个时间段的时间好像就不能了，
> 　比如我想在2000-05-05到2020-03-20这个时间段内选取一个时间点就不行了。
> 　更极限的在2000-05-05 12:20:31到2020-03-20 19:40:33这个时间段呢。
> 　作者可以开放个方法
> 　pickDate(Context context, @nullable Date initDate, Date witchPickVisible, Date startDate, Date endDate, final 　OnDatePickListener listener)
> 4：OnDatePickListener 回调的参数有点多，如果可以，希望返回DateWheelPicker？这样就可以直接通过picker.getSelectedYear()等获取想要的值。
> 5：application中全局统一style

1.在你的app的字符串资源文件添加时就解决你的问题
2.看BottomSheet中的方法
3.目前没有实现
4.可以考虑优化
5.目前Datapicker类中的静态方法是为了展示用法，看效果，所以style都在这里设置。

**Comment by yijiebuyi** [comment]
> > > > 首先谢谢作者的开源，这个框架确实比其他的框架滑动起来丝滑很多。
> > > > 之前因为这个问题没有达到我的预期，奈何自定义view我是个渣渣，只能用NumberPicker搞了组合控件使用。
> > > > 不过我刚下载了Demo就发现了一个问题，选择时间可以选择到59点，这个希望作者看一下。
> > > > 还有希望作者提供一些修改UI风格的方法，字体大小，颜色，阻尼等。
> > > 
> > > 
> > > 感谢反馈，问题已修复，见mk文档描述
> > 
> > 
> > 1：默认的小时单位，是“点”好，还是“时”好？
> > 2：HeadView有对外开放的方法吗，HeadView的backgroundColor，可否添加个中间的title？textColor，textSize等。
> > 3：pickDate选取时间只能获取前后几年的数据，如果我想获取某个时间段的时间好像就不能了，
> > 　比如我想在2000-05-05到2020-03-20这个时间段内选取一个时间点就不行了。
> > 　更极限的在2000-05-05 12:20:31到2020-03-20 19:40:33这个时间段呢。
> > 　作者可以开放个方法
> > 　pickDate(Context context, @nullable Date initDate, Date witchPickVisible, Date startDate, Date endDate, final 　OnDatePickListener listener)
> > 4：OnDatePickListener 回调的参数有点多，如果可以，希望返回DateWheelPicker？这样就可以直接通过picker.getSelectedYear()等获取想要的值。
> > 5：application中全局统一style
> 
> 1.在你的app的字符串资源文件添加时就解决你的问题
> 2.看BottomSheet中的方法
> 3.目前没有实现
> 4.可以考虑优化
> 5.目前Datapicker类中的静态方法是为了展示用法，看效果，所以style都在这里设置。

1.在你的app的字符串资源文件添加<string name="_hour">时</string>就解决你的问题

**Comment by yijiebuyi** [comment]
> > > 首先谢谢作者的开源，这个框架确实比其他的框架滑动起来丝滑很多。
> > > 之前因为这个问题没有达到我的预期，奈何自定义view我是个渣渣，只能用NumberPicker搞了组合控件使用。
> > > 不过我刚下载了Demo就发现了一个问题，选择时间可以选择到59点，这个希望作者看一下。
> > > 还有希望作者提供一些修改UI风格的方法，字体大小，颜色，阻尼等。
> > 
> > 
> > 感谢反馈，问题已修复，见mk文档描述
> 
> 1：默认的小时单位，是“点”好，还是“时”好？
> 2：HeadView有对外开放的方法吗，HeadView的backgroundColor，可否添加个中间的title？textColor，textSize等。
> 3：pickDate选取时间只能获取前后几年的数据，如果我想获取某个时间段的时间好像就不能了，
> 　比如我想在2000-05-05到2020-03-20这个时间段内选取一个时间点就不行了。
> 　更极限的在2000-05-05 12:20:31到2020-03-20 19:40:33这个时间段呢。
> 　作者可以开放个方法
> 　pickDate(Context context, @nullable Date initDate, Date witchPickVisible, Date startDate, Date endDate, final 　OnDatePickListener listener)
> 4：OnDatePickListener 回调的参数有点多，如果可以，希望返回DateWheelPicker？这样就可以直接通过picker.getSelectedYear()等获取想要的值。
> 5：application中全局统一style

1.在你的app的字符串资源文件添加_hour字符串，重写库中字符串_hour的值
2.看BottomSheet中的方法
3.目前没有实现
4.可以考虑优化
5.目前Datapicker类中的静态方法是为了展示用法，看效果，所以style都在这里设置。

**Comment by 32R34L** [comment]
如果参考Datapicker这个类在项目中使用的话写的代码太多了。
如果弄成静态方法工具类会不会内存泄漏？
有没有跟marterial-dialogs这个框架的使用方法链式调用一样的：
new MaterialDialog.Builder(this)
                .title("标题")
                .content("内容")
                .positiveText("确认")
                .negativeText("取消")
                .show();

**Comment by yijiebuyi** [comment]
> > > 首先谢谢作者的开源，这个框架确实比其他的框架滑动起来丝滑很多。
> > > 之前因为这个问题没有达到我的预期，奈何自定义view我是个渣渣，只能用NumberPicker搞了组合控件使用。
> > > 不过我刚下载了Demo就发现了一个问题，选择时间可以选择到59点，这个希望作者看一下。
> > > 还有希望作者提供一些修改UI风格的方法，字体大小，颜色，阻尼等。
> > 
> > 
> > 感谢反馈，问题已修复，见mk文档描述
> 
> 1：默认的小时单位，是“点”好，还是“时”好？
> 2：HeadView有对外开放的方法吗，HeadView的backgroundColor，可否添加个中间的title？textColor，textSize等。
> 3：pickDate选取时间只能获取前后几年的数据，如果我想获取某个时间段的时间好像就不能了，
> 　比如我想在2000-05-05到2020-03-20这个时间段内选取一个时间点就不行了。
> 　更极限的在2000-05-05 12:20:31到2020-03-20 19:40:33这个时间段呢。
> 　作者可以开放个方法
> 　pickDate(Context context, @nullable Date initDate, Date witchPickVisible, Date startDate, Date endDate, final 　OnDatePickListener listener)
> 4：OnDatePickListener 回调的参数有点多，如果可以，希望返回DateWheelPicker？这样就可以直接通过picker.getSelectedYear()等获取想要的值。
> 5：application中全局统一style

1.默认改为“时”，在你的app的字符串资源文件添加_hour字符串，重写库中字符串_hour的值
2.看BottomSheet中的方法，可以参考mk文件描述
3.目前没有实现
4.已优化
5.已优化

**Comment by yijiebuyi** [comment]
针对第3条，依赖1.2.0版本，即可实现   

/**
     * 获取日期 （某个时间段范围）
     *
     * @param context
     * @param initDate
     * @param mode
     * @param from     开始日期
     * @param to       结束日期
     * @param option
     * @param listener
     */
    public static void pickDate(Context context, @Nullable Date initDate, int mode,
                                long from, long to,
                                @Nullable PickOption option,
                                final OnDatePickListener listener) {

**Comment by yijiebuyi** [comment]
> > > 首先谢谢作者的开源，这个框架确实比其他的框架滑动起来丝滑很多。
> > > 之前因为这个问题没有达到我的预期，奈何自定义view我是个渣渣，只能用NumberPicker搞了组合控件使用。
> > > 不过我刚下载了Demo就发现了一个问题，选择时间可以选择到59点，这个希望作者看一下。
> > > 还有希望作者提供一些修改UI风格的方法，字体大小，颜色，阻尼等。
> > 
> > 
> > 感谢反馈，问题已修复，见mk文档描述
> 
> 1：默认的小时单位，是“点”好，还是“时”好？ 2：HeadView有对外开放的方法吗，HeadView的backgroundColor，可否添加个中间的title？textColor，textSize等。 3：pickDate选取时间只能获取前后几年的数据，如果我想获取某个时间段的时间好像就不能了， 　比如我想在2000-05-05到2020-03-20这个时间段内选取一个时间点就不行了。 　更极限的在2000-05-05 12:20:31到2020-03-20 19:40:33这个时间段呢。 　作者可以开放个方法 　pickDate(Context context, @nullable Date initDate, Date witchPickVisible, Date startDate, Date endDate, final 　OnDatePickListener listener) 4：OnDatePickListener 回调的参数有点多，如果可以，希望返回DateWheelPicker？这样就可以直接通过picker.getSelectedYear()等获取想要的值。 5：application中全局统一style

针对第3条，依赖1.2.0版本，即可实现

/**
* 获取日期 （某个时间段范围）
*
* @param context
* @param initDate
* @param mode
* @param from 开始日期
* @param to 结束日期
* @param option
* @param listener
*/
public static void pickDate(Context context, @nullable Date initDate, int mode,
long from, long to,
@nullable PickOption option,
final OnDatePickListener listener)
