### ISSUE TITLE
地区选择，只需要省市，不需要区或乡镇，需要怎么调用？

### ISSUE THREAD

**Issue by FreddyChen** [yijiebuyi/3DWheelPicker#2]

**Comment by yijiebuyi** [comment]
参照demo使用（目前默认使用的是加载的省市区的）
    public static <T> void pickData(Context context, @Nullable List<Integer> initIndex, @NonNull List<List<?>> srcData,
                                    @Nullable PickOption option, boolean wrapper,
                                    final OnMultiDataPickListener listener, final OnCascadeWheelListener cascadeListener)

自己构造一个没有区和乡镇的数据List

**Comment by yijiebuyi** [comment]
> _No description provided._

下个版本会优化

**Comment by yijiebuyi** [comment]
v1.1.2已完善
