### ISSUE TITLE
vivo手机滑动中再次点击列表，列表会回到下标零。无法正常使用

### ISSUE THREAD

**Issue by Lingdoctor** [yijiebuyi/3DWheelPicker#3]
![3DWheelPickerERROR](https://user-images.githubusercontent.com/45865740/103518080-1a73ba00-4eae-11eb-926f-795c0b37bf20.gif)
![vivo_phone_info](https://user-images.githubusercontent.com/45865740/103518241-5f97ec00-4eae-11eb-86bc-c160b6935184.png)
列表自动滑动中如果出现新的触摸事件，列表会回到下标零。无法正常使用。
QQ：1294374975.如果需要其他材料请联系我，请备注3D选择器。

**Comment by Lingdoctor** [comment]
如GIthub链接无法打开图片，请访问下方蓝奏云链接
https://wws.lanzous.com/iorVek1435i

**Comment by zzzsssbo** [comment]
我在华为和小米手机上没有发现这个问题，不知道是不是只有vivo上有这个问题，对比了其他的数据选择器，就这个体验最好，所以项目中准备使用这个，因为目前手边上没有vivo手机，所以也测不了你说的那个问题。

**Comment by Lingdoctor** [comment]
> 我在华为和小米手机上没有发现这个问题，不知道是不是只有vivo上有这个问题，对比了其他的数据选择器，就这个体验最好，所以项目中准备使用这个，因为目前手边上没有vivo手机，所以也测不了你说的那个问题。

会有这个问题，导致vivo oppo 无法使用，估计要做兼容，选择器不错，如果想要使用，最好拿个vivo测试一下

**Comment by yijiebuyi** [comment]
> > 我在华为和小米手机上没有发现这个问题，不知道是不是只有vivo上有这个问题，对比了其他的数据选择器，就这个体验最好，所以项目中准备使用这个，因为目前手边上没有vivo手机，所以也测不了你说的那个问题。
> 
> 会有这个问题，导致vivo oppo 无法使用，估计要做兼容，选择器不错，如果想要使用，最好拿个vivo测试一下

oppo上面测试过，没有问题，若有疑问，可以咨询QQ 530227088

**Comment by yijiebuyi** [comment]
v1.1.2已修复
