### ISSUE TITLE
如GIthub链接无法打开图片，请访问下方蓝奏云链接

### ISSUE THREAD

**Issue by Lingdoctor** [yijiebuyi/3DWheelPicker#4]
如GIthub链接无法打卡图片，请访问下方蓝奏云链接
https://wws.lanzous.com/iorVek1435i

_Originally posted by @Lingdoctor in https://github.com/yijiebuyi/3DWheelPicker/issues/3#issuecomment-753853704_

**Comment by yijiebuyi** [comment]
v1.1.2已修复
